import './globals.css'
import './fonts.css'
import  {GlobalStateProvider} from './context/GlobalStateProvider'
import NavBar from './components/home/NavBar'
import Footer from './components/home/Footer'
import LogoLoader from './components/Loaders/LogoLoader'

export const metadata = {
  title: 'Swasau Tech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-200`}>
          <GlobalStateProvider>
            <LogoLoader/>
            <NavBar/>
            {/* {children} */}
            <Footer/>
          </GlobalStateProvider>
      </body>
    </html>
  )
}
