import { Inter } from 'next/font/google'
import './globals.css'
import  {GlobalStateProvider} from './context/GlobalStateProvider'
import NavBar from './components/home/NavBar'
import Footer from './components/home/Footer'
import LogoLoader from './components/Loaders/LogoLoader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200`}>
          <GlobalStateProvider>
            <LogoLoader/>
            <NavBar/>
            {children}
            <Footer/>
          </GlobalStateProvider>
      </body>
    </html>
  )
}
